Hw05 avatars
Bohdan-morenec/nodejs-homework-rest-api pull request #8
Opened 2021-09-20 20:34 UTC by Bohdan-morenec

Добрый вечер. сделал

2021-09-20 21:11 UTC, Danil44 requested changes

2021-09-20 21:11 UTC, Danil44 commented on middleware/upload.js
> +    cd(null, renameOriginalname(file.originalname))
А яким чином викликається функція яка є константою і об'явлена нижче?

2021-09-20 21:27 UTC, Bohdan-morenec commented on middleware/upload.js
> +    cd(null, renameOriginalname(file.originalname))
ну якщо чесно, я навіть не замислювався чому воно працю, але воно працює, я тільки що перевірив. Я не знаю чи в ноді, можна писати багато функцій в одному файлі, в реакті ми таке постійно робили, а тут вчитель майже зовсім такого не робить, можна робити?

2021-09-20 21:32 UTC, Bohdan-morenec commented on middleware/upload.js
> +    cd(null, renameOriginalname(file.originalname))
може воно працює тому що, починає шукати константу в файлі, і все зупиняє поки її не знайде, ну я так думаю

2021-09-23 21:45 UTC, Danil44 approved these changes

2021-09-23 21:45 UTC, Danil44 commented on middleware/upload.js
> +    cd(null, renameOriginalname(file.originalname))
Ліпше поставити функцію вище

2021-09-26 13:13 UTC, merged